### ISSUE TITLE
System.NullReferenceException throwed on AssignOutputDialog when there are any existing parameterized property 

### ISSUE THREAD

**Issue by btyilmaz** [opentap/opentap#1740]
When a property is parameterized on the **test plan** and user tries to assign an output to any property  using "Assign Output" menu item, `System.NullReferenceException` is thrown by OpenTap.dll.

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.25.1

**Steps to reproduce the behavior:**

1. Add a test step with an output property (a property with the [Output] attribute)
2. Parameterize the output property on the test plan
3. Open the assign output dialog on any other test step's property using "Assign Output" menu item
4. Open the "Output" combobox to trigger the `System.NullReferenceException`.

**Additional context**

I think AssignOutputDialog class tries to show both the output property itself from the test step and the parameter from the test plan. That might be the issue on the dialog.

**Comment by rmadsen-ks** [comment]
@btyilmaz, 

Thanks for submitting an issue!

I was able to reproduce this.

**Comment by rmadsen-ks** [comment]
Hi @btyilmaz,

This issue has been fixed in the new release 9.26.0.

**Comment by btyilmaz** [comment]
Thank you @rmadsen-ks,

I saw the changed files in the commit history but issue persists and I think" OpenTAP.9.26.0+4ecb45bb.x64.Windows.TapPackage" does not contain the changes made in 9.26.0. 

Issue is resolved though, I tested it manually copying generated OpenTap.dll to the OpenTap directory.

**Comment by rmadsen-ks** [comment]
Hi @btyilmaz, sorry, I had the clear impression that this was included in the release. 

It will be included in a patch release in the near future.
