### ISSUE TITLE
Deprecated links on opentap.io

### ISSUE THREAD

**Issue by razvancoste** [opentap/opentap#489]
- [x] **License file moved to Github** ![image](https://user-images.githubusercontent.com/98153555/160127491-6263c925-2c1f-4d7c-9026-b1eaf3370e7f.png) 
- [ ] **Update documentation for GitHub also?** ![image](https://user-images.githubusercontent.com/98153555/160128527-566faaa4-c894-4eb8-a3ff-dafbb0a0ea2b.png) 
- [ ] **TUI still available on Gitlab?** ![image](https://user-images.githubusercontent.com/98153555/160129023-c69be71b-15f1-447c-9d9c-bc35ad203bea.png)

**Comment by g-galante** [comment]
- [ ] The [OpenTAP whitepaper](https://opentap.io/assets/whitepapers/OpenTAP-White-Paper-v2.pdf) linked from https://opentap.io/about:
```html
<a class="focus:outline-none focus-visible:ring focus-visible:ring-offset-2
                            inline-flex items-center py-3 px-4 border leading-none no-underline motion-safe:transition
                bg-primary border-primary text-white focus-visible:ring-primary hover:border-primary-500 hover:bg-primary-500
             
        " href="/assets/whitepapers/OpenTAP-White-Paper-v2.pdf" download="" title="Learn more" aria-label="Link to the OpenTAP Whitepaper">
        View Whitepaper
    </a>
```
still references the deprecated GitLab repository on page 18:
![image](https://user-images.githubusercontent.com/102026043/160367831-4486a340-12b8-4485-aee4-8b65cbeac462.png)

Please, let me know whether it's not ok to piggyback on this issue and you prefer that I open a new one.

**Comment by bdirenzo-keysight** [comment]
@rmadsen-ks I've fixed the opentap.io issues. For documentation, I believe TUI is still on Gitlab, and we will add CI/CD documentation for Github in the future.

**Comment by bdirenzo-keysight** [comment]
Breaking other tasks out into #494 and #495 and closing this one.

**Comment by g-galante** [comment]
Unfortunately I still get the version of the document shown above https://github.com/opentap/opentap/issues/489#issuecomment-1080447553.
Have you tested your modification?
I don't think it's a caching issue on my side.

**Comment by bdirenzo-keysight** [comment]
> Unfortunately I still get the version of the document shown above [#489 (comment)](https://github.com/opentap/opentap/issues/489#issuecomment-1080447553). Have you tested your modification? I don't think it's a caching issue on my side.

@g-galante that will take a little bit to be live. The rest should update immedaitely.

**Comment by bdirenzo-keysight** [comment]
@g-galante the links to whitepaper should be live

**Comment by g-galante** [comment]
Why *should*? Can you see the correct version at https://opentap.io/assets/whitepapers/OpenTAP-White-Paper-v2.pdf?
The `href` on https://opentap.io/about hasn't changed, and I keep seeing the stale version:
```
$ curl -I https://opentap.io/assets/whitepapers/OpenTAP-White-Paper-v2.pdf
HTTP/2 200 
server: nginx
date: Tue, 29 Mar 2022 15:41:15 GMT
content-type: application/pdf
content-length: 1158968
last-modified: Thu, 13 Jan 2022 23:47:42 GMT
etag: "61e0ba1e-11af38"
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
accept-ranges: bytes

```

**Comment by g-galante** [comment]
I had spotted the problem mentioned above https://github.com/opentap/opentap/issues/489#issuecomment-1080447553 when quickly scrolling through the document to get the 30,000-feet (over)view.

Later, while wating for the fix to materialize, I hovered the mouse over the next line:
> Documentation: doc.opentap.io

and I noticed that it was actually linking (and still currently links) to https://gitlab.com/OpenTAP/opentap.

Now, I've finally found the time to review the whole document more thoroughly and write my comments down in issue https://github.com/opentap/opentap/issues/587.
